services:
  - type: web
    name: algotrade-miniapp
    runtime: static
    buildCommand: ''
    staticPublishPath: ./public/mini-app
    pullRequestPreviewsEnabled: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
